"repository":
  "name": "php"
  "description": "[WIP] Development and Production-ready PHP Alpine Images for Docker with Multi-Architecture support"
  "homepage": "https://github.com/ghostwriter/php"
  "topics": "composer, docker, ghostwriter, php, php-cli, php-fpm, php-zts, xdebug"
  "has_issues": true
  "has_projects": false
  "has_wiki": false
  "has_downloads": true
  "default_branch": "main"
  "allow_squash_merge": true
  "allow_merge_commit": true
  "allow_rebase_merge": true
  "delete_branch_on_merge": true
  "enable_automated_security_fixes": true
  "enable_vulnerability_alerts": true
  "allow_auto_merge": true
  "allow_update_branch": true
  "web_commit_signoff_required": true
"milestones":
  - "title": "0.1.0"
    "description": "Minor release – targeting 0.1.x branch (semantic version: 0.1.0)"
    "state": "open"
  - "title": "1.0.0"
    "description": "Major release – targeting 1.0.x branch (semantic version: 1.0.0)"
    "state": "open"
