name: cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # Runs every hour.

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        type:
          # - 'docker'
          - 'container'
        name:
          - 'php'
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          delete-only-untagged-versions: 'true'
          min-versions-to-keep: 50
          package-name: ${{ matrix.name }}
          package-type: ${{ matrix.type }}
          # token: ${{ secrets.GHT }}
