name: cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *" # Runs At every 5th minute.

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        #type:
        #  - 'container'
        name:
          - 'php'
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-ghost-images: true
          delete-partial-images: true
          delete-untagged: true
          log-level: debug
          owner: ${{ github.repository_owner }}
          package: ${{ matrix.name }}
          repository: ${{ matrix.name }}
          validate: true
      #- uses: actions/delete-package-versions@v5
      #  with:
      #    ignore-versions: '^\d+\.\d+(?:-(?:zts|cli|fpm))?$'
      #    min-versions-to-keep: 100
      #    package-name: ${{ matrix.name }}
      #    package-type: ${{ matrix.type }}
      #    token: ${{ secrets.GHT }}
